In [2]:
import pandas as pd

# 데이터 전처리(preprocessing)
## 가. 누락 데이터 처리하기
  * 누락 데이터(missing value) : 값이 누락된 데이터
### 1. 누락된 데이터를 표현하는 용어
#### 가) NaN, null, na
#### 나) NaN : pandas의 read 함수(read_csv 등)를 이용해서 파일을 DataFrame이나 Series로 변환할 때, 누락 데이터를 표현하는 수
#### 다) null, na : 함수의 이름으로 사용

In [3]:
file_path = "./실습데이터/ns_202104.csv"
df = pd.read_csv(file_path)
display(df)

C:\Users\playdata2\AppData\Local\Temp\ipykernel_15396\1805308182.py:2: DtypeWarning: Columns (0: ISBN, 1: 세트 ISBN, 2: 주제분류번호) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
401677,401678,韓國現代詩大系,채만묵 編著,한국문화사,1996,9788977352971,9788977352988.0,NaN,3,811.608,1,0,1970-01-01
401678,401679,뉴 웨이브,제임스 모나코 지음,한나래,1996,9788985367448,9788985367424.0,NaN,2,688.04,1,0,1970-01-01
401679,401680,(최인훈 장편소설)화두,최인훈 지음,민음사,1994,9788937401596,9788937401589.0,NaN,2,813.6,1,0,1970-01-01
401680,401681,독일 문학과 세계 문학,吳漢鎭 編著,벽호,1995,9788947700368,9788947700405.0,NaN,3,809.05,2,0,1970-01-01
401681,401682,참으로 소중한 생각,김일상 지음,동문사,1995,9788970610092,9788970610092.0,0,1,814.6,0,0,1970-01-01

### 2. 누락된 데이터의 개수 확인 함수 : df.isnull().sum()
#### 가) isnull() 함수 : 누락 여부를 확인해서 bool 형식으로 전달하는 함수 
#### 나) sum() : 배열 값의 총합을 구하는 메서드

In [4]:
print(df.isnull().sum())

번호              0
도서명           403
저자            201
출판사          4795
발행년도           17
ISBN            0
세트 ISBN    339811
부가기호        76648
권          333415
주제분류번호      20322
도서권수            0
대출건수            0
등록일자            0
dtype: int64

### 3. 누락된 데이터 삭제하기: df.dropna(ignore_index)
#### 가) 행 또는 열에 누락 데이터(missing value, NaN)가 1개만 있어도 해당 행 제거
#### 나) ignore_index=True : 행 인덱스 자동 수정

In [5]:
display(df.dropna(ignore_index = True))

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,110,파친코,이민진 지음 ;이미정 옮김,문학사상,2018,9788970129815,9788970129808,0,1,843.6,1,0,2021-03-12
1,111,파친코,이민진 지음 ;이미정 옮김,문학사상,2018,9788970129822,9788970129808,0,2,843.6,1,0,2021-03-12
2,127,파친코,이민진 지음 ;이미정 옮김,문학사상,2018,9788970129815,9788970129808,0,1,843.6,1,0,2021-03-12
3,128,파친코,이민진 지음 ;이미정 옮김,문학사상,2018,9788970129815,9788970129808,0,1,843.6,1,0,2021-03-12
4,129,파친코,이민진 지음 ;이미정 옮김,문학사상,2018,9788970129822,9788970129808,0,2,843.6,1,0,2021-03-12
...,...,...,...,...,...,...,...,...,...,...,...,...,...
35822,401671,무량의경 해설,金鉉斗 지음,阿那,2004,9788989958130,9788989958116.0,0,1,223.54,0,0,1970-01-01
35823,401672,료마가 간다,시바 료타로 지음;이길진 옮김,창해,2003,9788979194005,9788979194005.0,0,9,833.6,0,0,1970-01-01
35824,401673,"미애와 루이, 318일간의 버스여행",최미애 글;장 루이 볼프 사진,자인,2003,9788989276210,9788989276210.0,0,1,980.24,0,0,1970-01-01
35825,401676,시귀,오노 후유미 지음;임희선 옮김,들녘,1999,9788975271366,9788975271335.0,(,3,833.6,0,0,1970-01-01
35826,401682,참으로 소중한 생각,김일상 지음,동문사,1995,9788970610092,9788970610092.0,0,1,814.6,0,0,1970-01-01

### 4. 누락된 데이터 바꾸기: 적당한 데이터 삽입
#### 가) df_cleaned = df.fillna("내용 없음") 
#### 나) df_cleaned = df.fillna(0)

In [6]:
df_cleaned1 = df.fillna("내용 없음")
display(df_cleaned1)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,내용 없음,내용 없음,내용 없음,내용 없음,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,내용 없음,내용 없음,내용 없음,내용 없음,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,내용 없음,내용 없음,내용 없음,내용 없음,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,내용 없음,내용 없음,내용 없음,내용 없음,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,내용 없음,내용 없음,내용 없음,내용 없음,1,0,2021-03-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
401677,401678,韓國現代詩大系,채만묵 編著,한국문화사,1996,9788977352971,9788977352988.0,내용 없음,3,811.608,1,0,1970-01-01
401678,401679,뉴 웨이브,제임스 모나코 지음,한나래,1996,9788985367448,9788985367424.0,내용 없음,2,688.04,1,0,1970-01-01
401679,401680,(최인훈 장편소설)화두,최인훈 지음,민음사,1994,9788937401596,9788937401589.0,내용 없음,2,813.6,1,0,1970-01-01
401680,401681,독일 문학과 세계 문학,吳漢鎭 編著,벽호,1995,9788947700368,9788947700405.0,내용 없음,3,809.05,2,0,1970-01-01
401681,401682,참으로 소중한 생각,김일상 지음,동문사,1995,9788970610092,9788970610092.0,0,1,814.6,0,0,1970-01-01

In [7]:
df_cleaned2 = df.fillna(0)
display(df_cleaned2)

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,0,0,0,0,1,0,2021-03-19
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,0,0,0,0,1,0,2021-03-19
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,0,0,0,0,1,0,2021-03-19
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,0,0,0,0,1,0,2021-03-19
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,0,0,0,0,1,0,2021-03-19
...,...,...,...,...,...,...,...,...,...,...,...,...,...
401677,401678,韓國現代詩大系,채만묵 編著,한국문화사,1996,9788977352971,9788977352988.0,0,3,811.608,1,0,1970-01-01
401678,401679,뉴 웨이브,제임스 모나코 지음,한나래,1996,9788985367448,9788985367424.0,0,2,688.04,1,0,1970-01-01
401679,401680,(최인훈 장편소설)화두,최인훈 지음,민음사,1994,9788937401596,9788937401589.0,0,2,813.6,1,0,1970-01-01
401680,401681,독일 문학과 세계 문학,吳漢鎭 編著,벽호,1995,9788947700368,9788947700405.0,0,3,809.05,2,0,1970-01-01
401681,401682,참으로 소중한 생각,김일상 지음,동문사,1995,9788970610092,9788970610092.0,0,1,814.6,0,0,1970-01-01

In [9]:
file_path2 = "./실습데이터/ad_performance.csv"
df2 = pd.read_csv(file_path2)

## 나. 중복되는 데이터를 그룹별로 모아서 처리하기
### 1. groupby()
#### 가) 중복된 데이터를 그룹별로 분할
#### 나) 분할된 각 그룹에 대하여 별도로 데이터를 처리하거나 그룹별 통계량을 확인하고자 할 때 사용
### 2. groupby(by).func()
#### 가) by=[co1, …] : 중복 여부를 확인하여 그룹별로 묶을 컬럼 지정
#### 나) func(함수) : 그룹별로 묶은 데이터에 대한 특정 함수 적용 예) sum(), mean()

In [11]:
channel_rev = df2.groupby(by="Channel")["Revenue"].mean()
print(channel_rev)

Channel
Facebook     1.055217e+06
Google       1.053278e+06
Instagram    1.060048e+06
Naver        1.084622e+06
Organic      1.069937e+06
Name: Revenue, dtype: float64

### 3. groupby(by).agg(새로운_컬럼명=('원본 컬럼명', '집계 함수'))
  * 기능 : 각 그룹별로 다양한 함수를 동시에 적용

In [12]:
channel_summary = df2.groupby('Channel').agg(
    total_cost = ('Cost', 'sum'),
    average_cost = ('Cost', 'mean'),
    total_revenue = ("Revenue", 'sum'),
    average_revenue = ("Revenue", 'mean')
)

print(channel_summary)

           total_cost   average_cost  total_revenue  average_revenue
Channel
Facebook    256579035  173481.430020     1560665319     1.055217e+06
Google      261593751  173701.029880     1586236276     1.053278e+06
Instagram    93910784  174880.417132      569245784     1.060048e+06
Naver       177725667  173729.879765     1109568326     1.084622e+06
Organic      78053282  171545.674725      486821439     1.069937e+06

In [13]:
file_path3 = "./실습데이터/weather.csv"
df3 = pd.read_csv(file_path3)
display(df3)

       temp  hum   atm  speed
0        17   34  1018    3.1
1        17   34  1018    3.1
2        17   34  1018    3.1
3        17   34  1018    3.1
4        17   34  1018    3.1
...     ...  ...   ...    ...
99995     9   71  1009    2.6
99996     9   71  1009    2.6
99997     9   71  1009    2.6
99998     9   71  1009    2.6
99999     9   71  1009    2.6

[100000 rows x 4 columns]

## 다. 이상치(outlier) 처리하기
### 1. 이상치 : 수집된 데이터 중에서 아주 작은 값이나 매우 큰 값
### 2. 이상치 측정 : IQR 이용
#### 가) 사분위수 : 순서대로 정렬된 데이터를 4구간으로 균등하게 분할 할 때 기준이 되는 수
#### 나) 백분위수 : 순서대로 정렬된 데이터를 균등하게 100 등분하는 경우 기준이 되는 수
#### 다) IQR(Interquartile range) : 사분위수의 75% 지점의 값과 25% 지점의 값 차이(Q3 - Q1)
#### 라) 정상 범위 데이터의 최소값(min) = Q1 – (1.5 * IQR)
#### 마) 정상 범위 데이터의 최대값(max) = Q3 + (1.5 * IQR)
#### 바) 이상치 : min, max를 벖어난 값
#### 라) 분위수(quantile) 구하기: quantile(q) 함수
##### 1) q : 원하는 백분위수 설정
##### 2) df.quantile(q) / df["col"].quantile(q)

In [18]:
q1 = df3.quantile(q=0.25)
q2 = df3.quantile(q=0.5)
q3 = df3.quantile(q=0.75)
print(q1)
print("-" * 80)
print(q2)
print("-" * 80)
print(q3)

temp       15.0
hum        66.0
atm      1002.0
speed       1.5
Name: 0.25, dtype: float64
--------------------------------------------------------------------------------
temp       16.0
hum        87.0
atm      1006.0
speed       3.1
Name: 0.5, dtype: float64
--------------------------------------------------------------------------------
temp       19.0
hum        93.0
atm      1007.0
speed       4.6
Name: 0.75, dtype: float64

In [20]:
iqr = q3 - q1
min_value = q1 - (iqr * 1.5)
max_value = q3 + (iqr * 1.5)
print(min_value)
print("-" * 80)
print(max_value)

temp       9.00
hum       25.50
atm      994.50
speed     -3.15
dtype: float64
--------------------------------------------------------------------------------
temp       25.00
hum       133.50
atm      1014.50
speed       9.25
dtype: float64

In [29]:
print(df3 < min_value)
print("-" * 80)
print(df3 > max_value)
print("-" * 80)
outlier_bool = (df3 < min_value) | (df3 > max_value)
print(outlier_bool)

        temp    hum    atm  speed
0      False  False  False  False
1      False  False  False  False
2      False  False  False  False
3      False  False  False  False
4      False  False  False  False
...      ...    ...    ...    ...
99995  False  False  False  False
99996  False  False  False  False
99997  False  False  False  False
99998  False  False  False  False
99999  False  False  False  False

[100000 rows x 4 columns]
--------------------------------------------------------------------------------
        temp    hum    atm  speed
0      False  False   True  False
1      False  False   True  False
2      False  False   True  False
3      False  False   True  False
4      False  False   True  False
...      ...    ...    ...    ...
99995  False  False  False  False
99996  False  False  False  False
99997  False  False  False  False
99998  False  False  False  False
99999  False  False  False  False

[100000 rows x 4 columns]
--------------------------------------------------------------------------------
        temp    hum    atm  speed
0      False  False   True  False
1      False  False   True  False
2      False  False   True  False
3      False  False   True  False
4      False  False   True  False
...      ...    ...    ...    ...
99995  False  False  False  False
99996  False  False  False  False
99997  False  False  False  False
99998  False  False  False  False
99999  False  False  False  False

[100000 rows x 4 columns]

In [40]:
print(outlier_bool.any())
print("-" * 80)
has_outlier = outlier_bool.any(axis=1)
print(has_outlier)

temp     True
hum      True
atm      True
speed    True
dtype: bool
--------------------------------------------------------------------------------
0         True
1         True
2         True
3         True
4         True
         ...
99995    False
99996    False
99997    False
99998    False
99999    False
Length: 100000, dtype: bool

In [41]:
output = ~has_outlier
print(output)
print("-" * 80)
arr_bool = output.values
print(arr_bool)

0        False
1        False
2        False
3        False
4        False
         ...
99995     True
99996     True
99997     True
99998     True
99999     True
Length: 100000, dtype: bool
--------------------------------------------------------------------------------
[False False False ...  True  True  True]

### 3. 이상치 처리 방법
#### 가) 제거
  * 전체 수치형 컬럼에 대한 Q1, Q3, IQR 한 번에 계산
  * 각 컬럼별 정상 범위 최소값/최대값 계산
  *  데이터프레임 전체에 대해 논리 연산자 적용, 이상치 여부 판단 → 블리언 DataFrame 생성
  * 어떤 컬럼에서든 이상치가 하나라도 있는 행 식별
  * 블리언 인덱싱을 통한 이상치가 없는 행만 필터링 후 인덱스 재설정

In [42]:
df3_normal = df3[arr_bool]
print(df3_normal)

       temp  hum   atm  speed
5193     23   30  1014    1.5
5194     23   30  1014    1.5
5195     23   30  1014    1.5
5196     23   30  1014    1.5
5197     23   30  1014    1.5
...     ...  ...   ...    ...
99995     9   71  1009    2.6
99996     9   71  1009    2.6
99997     9   71  1009    2.6
99998     9   71  1009    2.6
99999     9   71  1009    2.6

[91751 rows x 4 columns]

#### 나) 대체
  * 정상 범위 최소값 미만은 정상 범위 최소값으로, 정상 범위 최대값 초과는 정상 범위 최소값으로 일괄 대체
  * clip 함수 사용: df_clipped = df.clip(lower=min_val, upper=max_val, axis=1)