# 데이터 분석
## 가. 개념 : 데이터를 수집, 정제, 해석하여 숨겨진 패턴과 유용한 정보(인사이트)를 발견하고, 이를 바탕으로 미래의 발생 가능한 상황을 예측하고 최적의 의사결정을 내리는 일련의 과정
## 나. 분석과정
### 1. 데이터 수집 : 분석에 필요한 데이터 확보
### 2. 데이터 전처리(preprocessing) : 데이터를 분석에 적합한 형태로 만들어서 신뢰도를 높이는 작업
### 3. 데이터 탐색 : 그래프나 통계적인 방법을 이용, 데이터의 특징과 패턴을 파악
### 4. 모델링 : 수집, 정제된 데이터를 기반으로 수학적, 통계적인 방법을 사용하여 데이터 간의 관계를 파악하고, 새로운 데이터에 대해서 결과를 예측하거나 설명할 수 있는 규칙(model)을 만드는 과정
### 5. 분석 모델 평가

# numpy(넘파이)
## 가. 정의 : 수학적 계산을 위한 파이썬 라이브러리
## 나. 자료형 : 다차원 배열(ndarray) ↔ 파이썬 리스트
### 1. python list 자료형과 numpy 다차원 배열 자료 구조 비교
    * python list
        * 존재 목적 / 장점
        다양한 자료형의 데이터 혼합 저장:
        정수, 실수, 문자열, 심지어 다른 리스트 등 어떤 종류의 데이터든 하나의 리스트 안에 자유롭게 담을 수 있음
        * 요소별 수학 연산 : 불가능
    * numpy 다차원 배열
        * 존재 목적 / 장점
            * 단일 종류의 숫자 데이터 중심
            * 대규모 수치 데이터를 묶어서 빠르고 효율적으로 처리
        * 요소별 수학 연산 : 가능(최대 장점)
### 2. 주요 특징
#### 가) 압도적인 연산 성능과 효율성: 대량의 숫자 데이터를 매우 빠르게 처리한 수 있음
#### 나) 풍부한 수학적 연산 기능 제공: 사칙연산, 통계(평균, 합계, 표준편차), 선형 대수, 푸리에 변한 등 데이터 분석에 필수적인 다양한 수학 함수들을 제공

In [2]:
# 사용하기 : 라이브러리 임포트
# numpy 라이브러리를 import하고 앞으로 np라는 이름으로 부른다.
import numpy as np

In [ ]:
# np.array(data) 함수
## data = python 리스트 또는 튜플, python 리스트(튜플)로부터 생성
list_data = [1, 2, 3, 4, 5]
arr = np.array([1, 2, 3, 4, 5])
print(list_data, arr, sep = "\n")

[1, 2, 3, 4, 5]
[1 2 3 4 5]

In [4]:
# np.array 연산
arr = np.array([1, 2, 3, 4, 5])
print(arr)
arr = arr * 3
print(arr)
arr = arr + 1
print(arr)

[1 2 3 4 5]
[ 3  6  9 12 15]
[ 4  7 10 13 16]

In [ ]:
# np.array 통계
arr = np.array([1, 2, 3, 4, 5])
print(arr.mean()) # 평균값
print(np.median(arr)) # 중앙값(중위수)
print(arr.std()) # 표준편차
print(arr.var()) # 분산
print(np.percentile(arr, 50)) # 백분위수 (0~100)
print(np.quantile(arr, 0.5)) # 분위수 (0 ~ 1)

3.0
3.0
1.4142135623730951
2.0
3.0
3.0

In [6]:
# array 인덱싱
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)
print(arr[0])
print(arr[0][0])
print(arr[0, 2])

[[1 2 3]
 [4 5 6]]
[1 2 3]
1
3

In [8]:
# 1차원 array 슬라이싱
## 배열[start 인덱스 : stop 인덱스]
### start 인덱스부터 stop 인덱스 바로 전까지 값 추출 (start <= x < stop)
arr = np.array(range(10))
print(arr)
arr1 = arr[3:8]
print(arr1)

[0 1 2 3 4 5 6 7 8 9]
[3 4 5 6 7]

In [9]:
# 2차원 array 슬라이싱
## 배열[행 start 인덱스 : 행 stop 인덱스, 열 start 인덱스 : 열 stop 인덱스
arr = np.array([range(0, 10), range(10, 20), range(20, 30), range(30, 40)])
print(arr)
arr1 = arr[:, 4:9]
print(arr1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]]
[[ 4  5  6  7  8]
 [14 15 16 17 18]
 [24 25 26 27 28]
 [34 35 36 37 38]]

In [1]:
# 판다스(pandas)
## DataFrame 자료형 생성: csv 파일 처리

In [2]:
# 필요한 라이브러리 임포트
import pandas as pd

In [ ]:
# DataFrame 생성

## csv 파일 경로 생성
file_path='./실습데이터/ad_performance.csv'

## read_csv() 함수 호출 -> DataFrame 자료형 생성
df = pd.read_csv(file_path)

# 결과 확인
display(df)

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue
0,2025-01-01,Facebook,50s+,Male,15412,578,100308,27,723225
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303
3,2025-01-01,Organic,30s,Female,6866,686,81358,28,520546
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721
...,...,...,...,...,...,...,...,...,...
4995,2025-06-29,Organic,20s,Female,10064,933,180066,40,814096
4996,2025-06-29,Naver,40s,Male,5657,537,71261,7,256452
4997,2025-06-29,Organic,40s,Male,7331,378,159162,20,795243
4998,2025-06-29,Google,20s,Male,9272,124,173437,23,1293372
4999,2025-06-29,Naver,30s,Female,12688,733,193294,13,1000870

In [ ]:
# 행 인덱스 추출: 객체.index
info_index = df.index
print(f'DataFrame 행 인덱스: \n{info_index}')

print('-'*80)

# 컬럼 인덱스 추출: 객체.columns
info_columns = df.columns
print(f'DataFrame 컬럼 인덱스: \n{info_columns}')

print('-'*80)

# 값(데이터) 추출: 객체.values
info_values = df.values
print(f'DataFrame 값: \n{info_values}')

DataFrame 행 인덱스:
RangeIndex(start=0, stop=5000, step=1)
--------------------------------------------------------------------------------
DataFrame 컬럼 인덱스:
Index(['Date', 'Channel', 'Age_Group', 'Gender', 'Impressions', 'Clicks',
       'Cost', 'Conversions', 'Revenue'],
      dtype='str')
--------------------------------------------------------------------------------
DataFrame 값:
[['2025-01-01' 'Facebook' '50s+' ... 100308 27 723225]
 ['2025-01-01' 'Google' '20s' ... 103029 26 1680444]
 ['2025-01-01' 'Naver' '50s+' ... 158046 48 1580303]
 ...
 ['2025-06-29' 'Organic' '40s' ... 159162 20 795243]
 ['2025-06-29' 'Google' '20s' ... 173437 23 1293372]
 ['2025-06-29' 'Naver' '30s' ... 193294 13 1000870]]

In [5]:
# 특정 컬럼 인덱싱: 변수['컬럼명(컬럼 인덱스)'] -> 결과: Series 자료형 생성
channel = df['Channel']
print(channel)

0       Facebook
1         Google
2          Naver
3        Organic
4          Naver
          ...
4995     Organic
4996       Naver
4997     Organic
4998      Google
4999       Naver
Name: Channel, Length: 5000, dtype: str

In [6]:
# fancy 인덱싱: df['컬럼인덱스'] -> df[['컬럼1','컬럼3',...]] -> 결과: DataFrame 생성
df1 = df[['Channel','Clicks','Revenue']]
display(df1)

       Channel  Clicks  Revenue
0     Facebook     578   723225
1       Google     897  1680444
2        Naver     471  1580303
3      Organic     686   520546
4        Naver     525  1505721
...        ...     ...      ...
4995   Organic     933   814096
4996     Naver     537   256452
4997   Organic     378   795243
4998    Google     124  1293372
4999     Naver     733  1000870

[5000 rows x 3 columns]

In [7]:
# 특정 행과 컬럼 인덱싱

## 행 인덱스:4, 컬럼 인덱스: 'Revenue' -> df.loc[행 인덱스,열 인덱스]
data = df.loc[4,'Revenue']
print(f'행 인덱스: 4, 컬럼 인덱스: Revenue의 값: {data}')

행 인덱스: 4, 컬럼 인덱스: Revenue의 값: 1505721

In [8]:
# 컬럼 추가
df['CTR'] = df['Clicks'] / df['Impressions'] * 100

# 결과 확인
print('새로운 컬럼 추가 후 데이터프레임')
display(df)

새로운 컬럼 추가 후 데이터프레임

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue,CTR
0,2025-01-01,Facebook,50s+,Male,15412,578,100308,27,723225,3.750324
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444,7.481234
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303,2.545533
3,2025-01-01,Organic,30s,Female,6866,686,81358,28,520546,9.991261
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721,10.000000
...,...,...,...,...,...,...,...,...,...,...
4995,2025-06-29,Organic,20s,Female,10064,933,180066,40,814096,9.270668
4996,2025-06-29,Naver,40s,Male,5657,537,71261,7,256452,9.492664
4997,2025-06-29,Organic,40s,Male,7331,378,159162,20,795243,5.156186
4998,2025-06-29,Google,20s,Male,9272,124,173437,23,1293372,1.337360
4999,2025-06-29,Naver,30s,Female,12688,733,193294,13,1000870,5.777112

In [9]:
# ROAS(Return On Ad Spend: 광고비 대비 매출액) 컬럼 추가
df['ROAS'] = df['Revenue'] / df['Cost'] * 100

# 결과 확인
print('새로운 컬럼 추가 후 데이터프레임')
display(df)

새로운 컬럼 추가 후 데이터프레임

,Date,Channel,Age_Group,Gender,Impressions,Clicks,Cost,Conversions,Revenue,CTR,ROAS
0,2025-01-01,Facebook,50s+,Male,15412,578,100308,27,723225,3.750324,721.004307
1,2025-01-01,Google,20s,Male,11990,897,103029,26,1680444,7.481234,1631.039804
2,2025-01-01,Naver,50s+,Female,18503,471,158046,48,1580303,2.545533,999.900662
3,2025-01-01,Organic,30s,Female,6866,686,81358,28,520546,9.991261,639.821530
4,2025-01-01,Naver,30s,Male,5250,525,295050,23,1505721,10.000000,510.327402
...,...,...,...,...,...,...,...,...,...,...,...
4995,2025-06-29,Organic,20s,Female,10064,933,180066,40,814096,9.270668,452.109782
4996,2025-06-29,Naver,40s,Male,5657,537,71261,7,256452,9.492664,359.877072
4997,2025-06-29,Organic,40s,Male,7331,378,159162,20,795243,5.156186,499.643759
4998,2025-06-29,Google,20s,Male,9272,124,173437,23,1293372,1.337360,745.730150
4999,2025-06-29,Naver,30s,Female,12688,733,193294,13,1000870,5.777112,517.796724

In [10]:
# 분석 목표: Channel 컬럼의 항목별 빈도수 분석

## Channel 컬럼 인덱싱 -> df['Channel'] -> value_counts() 함수 적용
channel_counts = df['Channel'].value_counts()
print(f'Channel 컬럼의 항목별 빈도수 분석: \n{channel_counts}')

Channel 컬럼의 항목별 빈도수 분석:
Channel
Google       1506
Facebook     1479
Naver        1023
Instagram     537
Organic       455
Name: count, dtype: int64